### ISSUE TITLE
Setting of identity in .choriarc should take precedence over environment variables

### ISSUE THREAD

**Issue by benningm** [choria-io/mcorpc-ruby-support#129]
In the `Mcollective::Util::certname` method at:

https://github.com/choria-io/mcorpc-ruby-support/blob/95d5469be1e18775816a61390d8830db8e5ac107/lib/mcollective/util/choria.rb#L698

The Environment Variables take precedence over the configured value.

In general i would expect that something i explicitly configure takes precedence over Environment variables.

Order should be:

* @config.identity
* ENV['MCOLLECTIVE_USER']
* ENV['USER']

**Comment by ripienaar** [comment]
I don’t think so, you have defaults when nothing is set. Most often used specific setting is in a config file that’s harder to change but easier than a default. Then finally a way to make adhoc changes for individual invocations when you just want to change something but after revert to configured behaviour. 

In the absence of a flag the MCOLLECTIVE_USER or so gives you that adhoc override ability.

**Comment by benningm** [comment]
Okay, maybe MCOLLECTIVE_USER should be the first.

But ENV['USER'] having a higher priority than the config option makes the config option almost useless as $USER is almost always set.

**Comment by ripienaar** [comment]
Maybe tell me what the problem you're having is? 

The behaviour is intentional we just don't support setting identity for users in configuration. The identity configuration is only consulted when running as root (ie. the old mcollectived, even thats never being called anymore since that doesnt exist anymore), we dont support running the client libraries as root.  So choria does in effect require the USER variable to be set, or if for some reason not you have the `MCOLLECTIVE_CERTNAME` variable
